import '../invoicethree_one_screen/widgets/invoicethreeone_item_widget.dart';import 'bloc/invoicethree_one_bloc.dart';import 'models/invoicethree_one_model.dart';import 'models/invoicethreeone_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_circleimage.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle_five.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle_four.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_trailing_iconbutton.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_bottom_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_search_view.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class InvoicethreeOneScreen extends StatelessWidget {InvoicethreeOneScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<InvoicethreeOneBloc>(create: (context) => InvoicethreeOneBloc(InvoicethreeOneState(invoicethreeOneModelObj: InvoicethreeOneModel()))..add(InvoicethreeOneInitialEvent()), child: InvoicethreeOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 15.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 22.h, right: 22.h, bottom: 5.v), child: Column(children: [BlocSelector<InvoicethreeOneBloc, InvoicethreeOneState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search_here".tr);}), SizedBox(height: 32.v), _buildInvoiceThreeOne(context)]))))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 75.h, leading: AppbarLeadingCircleimage(imagePath: ImageConstant.imgRectangle18623, margin: EdgeInsets.only(left: 24.h, top: 2.v, bottom: 2.v), onTap: () {onTapCircleImage(context);}), title: Padding(padding: EdgeInsets.only(left: 7.h), child: Column(children: [AppbarSubtitleFive(text: "lbl_a_z_pharmacy".tr), AppbarSubtitleFour(text: "lbl_egypt2".tr, margin: EdgeInsets.only(right: 65.h))])), actions: [AppbarTrailingIconbutton(imagePath: ImageConstant.img8134640GiftBi, margin: EdgeInsets.fromLTRB(23.h, 2.v, 23.h, 5.v), onTap: () {onTapGiftBi(context);})]); } 
/// Section Widget
Widget _buildInvoiceThreeOne(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h), child: BlocSelector<InvoicethreeOneBloc, InvoicethreeOneState, InvoicethreeOneModel?>(selector: (state) => state.invoicethreeOneModelObj, builder: (context, invoicethreeOneModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 111.v, crossAxisCount: 2, mainAxisSpacing: 29.h, crossAxisSpacing: 29.h), physics: NeverScrollableScrollPhysics(), itemCount: invoicethreeOneModelObj?.invoicethreeoneItemList.length ?? 0, itemBuilder: (context, index) {InvoicethreeoneItemModel model = invoicethreeOneModelObj?.invoicethreeoneItemList[index] ?? InvoicethreeoneItemModel(); return InvoicethreeoneItemWidget(model, onTapMywallet: () {onTapMywallet(context);});});})); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {}); } 
/// Navigates to the brandInfotwoTwoScreen when the action is triggered.
onTapMywallet(BuildContext context) { NavigatorService.pushNamed(AppRoutes.brandInfotwoTwoScreen); } 
/// Navigates to the profileScreen when the action is triggered.
onTapCircleImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
/// Navigates to the categoryInfoOneScreen when the action is triggered.
onTapGiftBi(BuildContext context) { NavigatorService.pushNamed(AppRoutes.categoryInfoOneScreen, ); } 
 }
