import 'bloc/brand_infotwo_eleven_bloc.dart';import 'models/brand_infotwo_eleven_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class BrandInfotwoElevenScreen extends StatelessWidget {const BrandInfotwoElevenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoElevenBloc>(create: (context) => BrandInfotwoElevenBloc(BrandInfotwoElevenState(brandInfotwoElevenModelObj: BrandInfotwoElevenModel()))..add(BrandInfotwoElevenInitialEvent()), child: BrandInfotwoElevenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<BrandInfotwoElevenBloc, BrandInfotwoElevenState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 17.v), child: Column(children: [Container(width: 247.h, margin: EdgeInsets.symmetric(horizontal: 57.h), padding: EdgeInsets.symmetric(horizontal: 41.h, vertical: 21.v), decoration: AppDecoration.outlineGray6003f012.copyWith(borderRadius: BorderRadiusStyle.roundedBorder28), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_remaining_uploads".tr, style: CustomTextStyles.titleMediumWhiteA70016), SizedBox(height: 7.v), Align(alignment: Alignment.center, child: Text("lbl_402".tr, style: CustomTextStyles.titleMediumWhiteA70016)), SizedBox(height: 3.v)])), SizedBox(height: 41.v), _buildRowFourteen(context), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 20.v, bottom: 24.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_my_ads".tr)); } 
/// Section Widget
Widget _buildRowFourteen(BuildContext context) { return Container(margin: EdgeInsets.only(left: 9.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.outlineRed7001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder17), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgVector, height: 14.v, width: 18.h, margin: EdgeInsets.only(top: 7.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 9.h, top: 4.v), child: Text("lbl_upgrade_package".tr, style: CustomTextStyles.titleMediumRed700Bold)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowLeftRed700, height: 15.adaptSize, width: 15.adaptSize, margin: EdgeInsets.only(top: 6.v, bottom: 7.v))])); } 
/// Navigates to the invoicethreeOneScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.invoicethreeOneScreen, ); } 
 }
