import '../brand_infotwo_seventeen_screen/widgets/productcard7_item_widget.dart';import 'bloc/brand_infotwo_seventeen_bloc.dart';import 'models/brand_infotwo_seventeen_model.dart';import 'models/productcard7_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_title.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class BrandInfotwoSeventeenScreen extends StatelessWidget {const BrandInfotwoSeventeenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoSeventeenBloc>(create: (context) => BrandInfotwoSeventeenBloc(BrandInfotwoSeventeenState(brandInfotwoSeventeenModelObj: BrandInfotwoSeventeenModel()))..add(BrandInfotwoSeventeenInitialEvent()), child: BrandInfotwoSeventeenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(left: 22.h, top: 15.v, right: 22.h), child: BlocSelector<BrandInfotwoSeventeenBloc, BrandInfotwoSeventeenState, BrandInfotwoSeventeenModel?>(selector: (state) => state.brandInfotwoSeventeenModelObj, builder: (context, brandInfotwoSeventeenModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 319.v, crossAxisCount: 2, mainAxisSpacing: 21.h, crossAxisSpacing: 21.h), physics: NeverScrollableScrollPhysics(), itemCount: brandInfotwoSeventeenModelObj?.productcard7ItemList.length ?? 0, itemBuilder: (context, index) {Productcard7ItemModel model = brandInfotwoSeventeenModelObj?.productcard7ItemList[index] ?? Productcard7ItemModel(); return Productcard7ItemWidget(model);});})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 23.v, bottom: 21.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_favorite2".tr)); } 
/// Navigates to the invoicethreeOneScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.invoicethreeOneScreen, ); } 
 }
