import '../sign_up_two_bottomsheet/widgets/fiftyone_item_widget.dart';import 'bloc/sign_up_two_bloc.dart';import 'models/fiftyone_item_model.dart';import 'models/sign_up_two_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class SignUpTwoBottomsheet extends StatelessWidget {const SignUpTwoBottomsheet({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SignUpTwoBloc>(create: (context) => SignUpTwoBloc(SignUpTwoState(signUpTwoModelObj: SignUpTwoModel()))..add(SignUpTwoInitialEvent()), child: SignUpTwoBottomsheet()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return Container(width: 413.h, padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 24.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildYourBusinessSpecialization(context), SizedBox(height: 85.v), _buildContinue(context), SizedBox(height: 42.v)])); } 
/// Section Widget
Widget _buildYourBusinessSpecialization(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h), child: Column(children: [Container(height: 7.v, width: 114.h, decoration: BoxDecoration(color: appTheme.gray5005e, borderRadius: BorderRadius.circular(3.h))), SizedBox(height: 13.v), Text("msg_your_business_specialization".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001_1), SizedBox(height: 28.v), BlocSelector<SignUpTwoBloc, SignUpTwoState, SignUpTwoModel?>(selector: (state) => state.signUpTwoModelObj, builder: (context, signUpTwoModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 111.v, crossAxisCount: 2, mainAxisSpacing: 29.h, crossAxisSpacing: 29.h), physics: NeverScrollableScrollPhysics(), itemCount: signUpTwoModelObj?.fiftyoneItemList.length ?? 0, itemBuilder: (context, index) {FiftyoneItemModel model = signUpTwoModelObj?.fiftyoneItemList[index] ?? FiftyoneItemModel(); return FiftyoneItemWidget(model);});})])); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 20.h, right: 14.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 8.v), child: Text("lbl_continue".tr, style: theme.textTheme.headlineMedium)), CustomIconButton(height: 55.adaptSize, width: 55.adaptSize, padding: EdgeInsets.all(19.h), onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))])); } 
/// Navigates to the signUp2IfItFromSaudiArabiaScreen when the action is triggered.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUp2IfItFromSaudiArabiaScreen, ); } 
 }
