import 'bloc/brand_infotwo_sixteen_bloc.dart';import 'models/brand_infotwo_sixteen_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/core/utils/validation_functions.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_drop_down.dart';import 'package:dondondony38_s_application1/widgets/custom_elevated_button.dart';import 'package:dondondony38_s_application1/widgets/custom_text_form_field.dart';import 'package:dotted_border/dotted_border.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class BrandInfotwoSixteenScreen extends StatelessWidget {BrandInfotwoSixteenScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoSixteenBloc>(create: (context) => BrandInfotwoSixteenBloc(BrandInfotwoSixteenState(brandInfotwoSixteenModelObj: BrandInfotwoSixteenModel()))..add(BrandInfotwoSixteenInitialEvent()), child: BrandInfotwoSixteenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 25.v), child: Padding(padding: EdgeInsets.only(left: 23.h, right: 18.h, bottom: 5.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_first".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001Medium_2)), SizedBox(height: 15.v), _buildFirstName(context), SizedBox(height: 26.v), _buildProductDescription(context), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<BrandInfotwoSixteenBloc, BrandInfotwoSixteenState, BrandInfotwoSixteenModel?>(selector: (state) => state.brandInfotwoSixteenModelObj, builder: (context, brandInfotwoSixteenModelObj) {return CustomDropDown(hintText: "lbl_select_category".tr, items: brandInfotwoSixteenModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<BrandInfotwoSixteenBloc>().add(ChangeDropDownEvent(value: value));});})), SizedBox(height: 26.v), _buildExpiryDate(context), SizedBox(height: 26.v), _buildPrice(context), SizedBox(height: 26.v), _buildQuantity(context), SizedBox(height: 26.v), _buildChoosePhoto(context), SizedBox(height: 51.v), _buildAddAnotherOne(context), SizedBox(height: 34.v), _buildSave(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 21.v, bottom: 20.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_add_products".tr)); } 
/// Section Widget
Widget _buildFirstName(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<BrandInfotwoSixteenBloc, BrandInfotwoSixteenState, TextEditingController?>(selector: (state) => state.firstNameController, builder: (context, firstNameController) {return CustomTextFormField(controller: firstNameController, hintText: "msg_please_enter_product".tr, hintStyle: CustomTextStyles.bodySmallPoppinsGray700, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 19.v));})); } 
/// Section Widget
Widget _buildProductDescription(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<BrandInfotwoSixteenBloc, BrandInfotwoSixteenState, TextEditingController?>(selector: (state) => state.productDescriptionController, builder: (context, productDescriptionController) {return CustomTextFormField(controller: productDescriptionController, hintText: "msg_product_description".tr, hintStyle: CustomTextStyles.bodySmallPoppinsGray700, maxLines: 5, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 21.v));})); } 
/// Section Widget
Widget _buildExpiryDate(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<BrandInfotwoSixteenBloc, BrandInfotwoSixteenState, TextEditingController?>(selector: (state) => state.expiryDateController, builder: (context, expiryDateController) {return CustomTextFormField(controller: expiryDateController, hintText: "lbl_expiry_date".tr, hintStyle: CustomTextStyles.bodySmallPoppinsGray700, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 16.v, 19.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgClaritydatesolid, height: 23.adaptSize, width: 23.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 58.v), contentPadding: EdgeInsets.only(left: 17.h, top: 19.v, bottom: 19.v));})); } 
/// Section Widget
Widget _buildPrice(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<BrandInfotwoSixteenBloc, BrandInfotwoSixteenState, TextEditingController?>(selector: (state) => state.priceController, builder: (context, priceController) {return CustomTextFormField(controller: priceController, hintText: "lbl_unit_price".tr, hintStyle: CustomTextStyles.bodySmallPoppinsGray700, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v));})); } 
/// Section Widget
Widget _buildQuantity(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 6.h), child: BlocSelector<BrandInfotwoSixteenBloc, BrandInfotwoSixteenState, TextEditingController?>(selector: (state) => state.quantityController, builder: (context, quantityController) {return CustomTextFormField(controller: quantityController, hintText: "lbl_quantity2".tr, hintStyle: CustomTextStyles.bodySmallPoppinsGray700, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 19.v));})); } 
/// Section Widget
Widget _buildChoosePhoto(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_choose_photo".tr, style: CustomTextStyles.bodyMedium_1), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 6.h), child: DottedBorder(color: appTheme.blueGray700, padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, radius: Radius.circular(10), borderType: BorderType.RRect, dashPattern: [8, 8], child: Container(padding: EdgeInsets.symmetric(horizontal: 143.h, vertical: 24.v), decoration: AppDecoration.outlineBlueGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup18401, height: 35.adaptSize, width: 35.adaptSize), SizedBox(height: 3.v), Text("lbl_attach_photo".tr, style: CustomTextStyles.bodySmallPoppinsBluegray300)]))))]); } 
/// Section Widget
Widget _buildAddAnotherOne(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 3.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 14.v), decoration: AppDecoration.outlineRed7002.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 5.v, bottom: 1.v), child: Text("lbl_add_anther_one".tr, style: CustomTextStyles.titleSmallPoppins)), CustomImageView(imagePath: ImageConstant.imgIcRoundPlus, height: 25.adaptSize, width: 25.adaptSize, margin: EdgeInsets.only(right: 5.h, bottom: 1.v))])); } 
/// Section Widget
Widget _buildSave(BuildContext context) { return CustomElevatedButton(height: 57.v, text: "lbl_save".tr, margin: EdgeInsets.only(left: 9.h, right: 3.h), buttonStyle: CustomButtonStyles.outlinePrimaryTL171); } 
/// Navigates to the brandInfotwoEightScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.brandInfotwoEightScreen, ); } 
 }
