import '../invoicethree_screen/widgets/productcardlist2_item_widget.dart';import 'bloc/invoicethree_bloc.dart';import 'models/invoicethree_model.dart';import 'models/productcardlist2_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/custom_bottom_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_elevated_button.dart';import 'package:dondondony38_s_application1/widgets/custom_outlined_button.dart';import 'package:dondondony38_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class InvoicethreeScreen extends StatelessWidget {InvoicethreeScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<InvoicethreeBloc>(create: (context) => InvoicethreeBloc(InvoicethreeState(invoicethreeModelObj: InvoicethreeModel()))..add(InvoicethreeInitialEvent()), child: InvoicethreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 23.v), _buildAzPharmacyRow(context), SizedBox(height: 40.v), SizedBox(height: 729.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [_buildProductCardList(context), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 24.v), decoration: AppDecoration.outlineGray50087.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, children: [Container(height: 7.v, width: 114.h, decoration: BoxDecoration(color: appTheme.gray5005e, borderRadius: BorderRadius.circular(3.h))), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(left: 9.h), child: BlocSelector<InvoicethreeBloc, InvoicethreeState, TextEditingController?>(selector: (state) => state.coupondiscountsalevouchericonOController, builder: (context, coupondiscountsalevouchericonOController) {return CustomTextFormField(controller: coupondiscountsalevouchericonOController, hintText: "lbl_1234at3".tr, hintStyle: CustomTextStyles.titleMedium16, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(12.h, 17.v, 13.h, 18.v), child: CustomImageView(imagePath: ImageConstant.img3702395Coupon, height: 27.v, width: 29.h)), prefixConstraints: BoxConstraints(maxHeight: 62.v));})), SizedBox(height: 6.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("msg_additional_discount".tr, style: CustomTextStyles.titleSmallPoppinsPrimaryMedium))), SizedBox(height: 15.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 18.h), child: Text("lbl_payment_summary".tr, style: CustomTextStyles.titleMediumSemiBold))), SizedBox(height: 8.v), _buildTotalBeforeDiscount(context), SizedBox(height: 7.v), _buildTotalAfterDiscount(context), SizedBox(height: 9.v), _buildCouponDiscount(context), SizedBox(height: 25.v), Divider(indent: 19.h, endIndent: 15.h), SizedBox(height: 20.v), _buildTotalRow(context), SizedBox(height: 23.v), _buildAddItemRow(context), SizedBox(height: 23.v)])))]))])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
Widget _buildAzPharmacyRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgRectangle18623, height: 51.adaptSize, width: 51.adaptSize, radius: BorderRadius.circular(25.h), onTap: () {onTapImgCircleImage(context);}), GestureDetector(onTap: () {onTapAZPharmacy(context);}, child: Padding(padding: EdgeInsets.only(left: 7.h, top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_a_z_pharmacy".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001SemiBold), Text("lbl_egypt2".tr, style: CustomTextStyles.bodyMediumBlack90001_1)]))), Spacer(), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.only(bottom: 3.v), color: appTheme.gray50, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder7), child: Container(height: 48.v, width: 53.h, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 9.v), decoration: AppDecoration.fillGray50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.img8134640GiftBi, height: 21.adaptSize, width: 21.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(bottom: 1.v)), Align(alignment: Alignment.topLeft, child: Container(height: 13.adaptSize, width: 13.adaptSize, decoration: BoxDecoration(color: appTheme.red700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.whiteA700, width: 1.h)))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_1".tr, style: theme.textTheme.labelSmall)))])))])); } 
/// Section Widget
Widget _buildProductCardList(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 368.v), child: BlocSelector<InvoicethreeBloc, InvoicethreeState, InvoicethreeModel?>(selector: (state) => state.invoicethreeModelObj, builder: (context, invoicethreeModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 14.v);}, itemCount: invoicethreeModelObj?.productcardlist2ItemList.length ?? 0, itemBuilder: (context, index) {Productcardlist2ItemModel model = invoicethreeModelObj?.productcardlist2ItemList[index] ?? Productcardlist2ItemModel(); return Productcardlist2ItemWidget(model);});}))); } 
/// Section Widget
Widget _buildTotalBeforeDiscount(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 22.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("msg_total_before_discount".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_50_50".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001))])); } 
/// Section Widget
Widget _buildTotalAfterDiscount(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 21.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("msg_total_after_discount".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)), Padding(padding: EdgeInsets.only(left: 3.h, top: 2.v, bottom: 3.v), child: Text("lbl_202".tr, style: CustomTextStyles.bodySmallPoppinsBlack90001)), Spacer(), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_30_50".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001))])); } 
/// Section Widget
Widget _buildCouponDiscount(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 19.h, right: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_coupon_discount".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001), Text("lbl_05_00".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)])); } 
/// Section Widget
Widget _buildTotalRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_total".tr, style: CustomTextStyles.titleMediumPrimarySemiBold), Text("lbl_25_50".tr, style: CustomTextStyles.titleMediumPrimarySemiBold)])); } 
/// Section Widget
Widget _buildAddItemRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 5.h, right: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "lbl_add_item".tr, margin: EdgeInsets.only(right: 15.h), onPressed: () {onTapAddItem(context);})), Expanded(child: CustomElevatedButton(height: 45.v, text: "lbl_checkout".tr, margin: EdgeInsets.only(left: 15.h), buttonStyle: CustomButtonStyles.fillOnError))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {}); } 
/// Navigates to the profileScreen when the action is triggered.
onTapImgCircleImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
/// Navigates to the profileScreen when the action is triggered.
onTapAZPharmacy(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
/// Navigates to the homeFourContainerScreen when the action is triggered.
onTapAddItem(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeFourContainerScreen, ); } 
 }
