import '../brand_infotwo_three_screen/widgets/productlisting_item_widget.dart';import 'bloc/brand_infotwo_three_bloc.dart';import 'models/brand_infotwo_three_model.dart';import 'models/productlisting_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class BrandInfotwoThreeScreen extends StatelessWidget {const BrandInfotwoThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoThreeBloc>(create: (context) => BrandInfotwoThreeBloc(BrandInfotwoThreeState(brandInfotwoThreeModelObj: BrandInfotwoThreeModel()))..add(BrandInfotwoThreeInitialEvent()), child: BrandInfotwoThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 18.v), child: Column(children: [_buildProductListing(context), SizedBox(height: 319.v), CustomElevatedButton(height: 56.v, width: 210.h, text: "lbl_new_services".tr, rightIcon: Container(margin: EdgeInsets.only(left: 29.h), child: CustomImageView(imagePath: ImageConstant.imgArrowLeftWhiteA700, height: 15.adaptSize, width: 15.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimaryTL171, onPressed: () {onTapNewServices(context);}, alignment: Alignment.centerRight), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 22.v, bottom: 22.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarSubtitle(text: "msg_medical_services".tr)); } 
/// Section Widget
Widget _buildProductListing(BuildContext context) { return SizedBox(height: 259.v, child: BlocSelector<BrandInfotwoThreeBloc, BrandInfotwoThreeState, BrandInfotwoThreeModel?>(selector: (state) => state.brandInfotwoThreeModelObj, builder: (context, brandInfotwoThreeModelObj) {return ListView.separated(padding: EdgeInsets.symmetric(horizontal: 5.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 14.h);}, itemCount: brandInfotwoThreeModelObj?.productlistingItemList.length ?? 0, itemBuilder: (context, index) {ProductlistingItemModel model = brandInfotwoThreeModelObj?.productlistingItemList[index] ?? ProductlistingItemModel(); return ProductlistingItemWidget(model);});})); } 
/// Navigates to the invoicethreeOneScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.invoicethreeOneScreen, ); } 
/// Navigates to the brandInfotwoEighteenScreen when the action is triggered.
onTapNewServices(BuildContext context) { NavigatorService.pushNamed(AppRoutes.brandInfotwoEighteenScreen, ); } 
 }
