import 'bloc/sign_up_five_bloc.dart';import 'models/sign_up_five_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/custom_icon_button.dart';import 'package:dondondony38_s_application1/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class SignUpFiveBottomsheet extends StatelessWidget {const SignUpFiveBottomsheet({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SignUpFiveBloc>(create: (context) => SignUpFiveBloc(SignUpFiveState(signUpFiveModelObj: SignUpFiveModel()))..add(SignUpFiveInitialEvent()), child: SignUpFiveBottomsheet()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return Container(width: 411.h, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 18.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Align(alignment: Alignment.center, child: Container(height: 7.v, width: 114.h, decoration: BoxDecoration(color: appTheme.gray5005e, borderRadius: BorderRadius.circular(3.h)))), SizedBox(height: 13.v), Align(alignment: Alignment.center, child: Text("lbl_your_region2".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001_1)), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 3.h), child: BlocSelector<SignUpFiveBloc, SignUpFiveState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl".tr, contentPadding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 12.v));})), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Container(height: 28.v, width: 123.h, margin: EdgeInsets.only(left: 5.h), child: Stack(alignment: Alignment.bottomLeft, children: [CustomImageView(imagePath: ImageConstant.imgTypcnLocation, height: 26.v, width: 25.h, alignment: Alignment.topRight), Align(alignment: Alignment.bottomLeft, child: Text("lbl_show_on_map".tr, style: CustomTextStyles.bodyMediumRed700))]))), SizedBox(height: 17.v), _buildAlsharqaCounterRow(context), SizedBox(height: 13.v), Divider(color: appTheme.blueGray200, indent: 27.h, endIndent: 4.h), SizedBox(height: 11.v), _buildAlsharqaCounterRow2(context), SizedBox(height: 13.v), Divider(color: appTheme.blueGray200, indent: 30.h, endIndent: 4.h), SizedBox(height: 13.v), _buildAlsharqaCounterRow3(context), SizedBox(height: 34.v), Padding(padding: EdgeInsets.only(right: 16.h), child: CustomIconButton(height: 55.adaptSize, width: 55.adaptSize, padding: EdgeInsets.all(19.h), onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftWhiteA700))), SizedBox(height: 95.v)])); } 
/// Section Widget
Widget _buildAlsharqaCounterRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 27.h, right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_alsharqa_34".tr, style: CustomTextStyles.bodyMediumErrorContainer), Text("msg_ahmed_maher_street".tr, style: CustomTextStyles.bodySmallPoppinsErrorContainer_1)])), Padding(padding: EdgeInsets.only(bottom: 18.v), child: Text("lbl_568_km".tr, style: CustomTextStyles.bodySmallPoppinsErrorContainer))])); } 
/// Section Widget
Widget _buildAlsharqaCounterRow2(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 27.h, right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_alsharqa_34".tr, style: CustomTextStyles.bodyMediumErrorContainer), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_ahmed_maher_street".tr, style: CustomTextStyles.bodySmallPoppinsErrorContainer_1))])), Padding(padding: EdgeInsets.only(bottom: 20.v), child: Text("lbl_568_km".tr, style: CustomTextStyles.bodySmallPoppinsErrorContainer))])); } 
/// Section Widget
Widget _buildAlsharqaCounterRow3(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 27.h, right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 35.v, width: 160.h, margin: EdgeInsets.only(top: 1.v), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Text("lbl_alsharqa_34".tr, style: CustomTextStyles.bodyMediumErrorContainer)), Align(alignment: Alignment.bottomCenter, child: Text("msg_ahmed_maher_street".tr, style: CustomTextStyles.bodySmallPoppinsErrorContainer_1))])), Padding(padding: EdgeInsets.only(bottom: 19.v), child: Text("lbl_568_km".tr, style: CustomTextStyles.bodySmallPoppinsErrorContainer))])); } 
/// Navigates to the signUpThreeScreen when the action is triggered.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUpThreeScreen, ); } 
 }
