import '../brand_infotwo_screen/widgets/notificationlist_item_widget.dart';import 'bloc/brand_infotwo_bloc.dart';import 'models/brand_infotwo_model.dart';import 'models/notificationlist_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;class BrandInfotwoScreen extends StatelessWidget {const BrandInfotwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoBloc>(create: (context) => BrandInfotwoBloc(BrandInfotwoState(brandInfotwoModelObj: BrandInfotwoModel()))..add(BrandInfotwoInitialEvent()), child: BrandInfotwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 21.h), child: Column(children: [SizedBox(height: 20.v), _buildUploadSection(context), SizedBox(height: 22.v), CustomElevatedButton(height: 46.v, width: 226.h, text: "lbl_deposit_money".tr, buttonStyle: CustomButtonStyles.fillOnError), SizedBox(height: 32.v), _buildSubjectsRow(context), SizedBox(height: 17.v), _buildNotificationList(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 20.v, bottom: 24.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_my_wallet".tr)); } 
/// Section Widget
Widget _buildUploadSection(BuildContext context) { return Container(width: 358.h, margin: EdgeInsets.only(left: 9.h, right: 4.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup336), fit: BoxFit.cover)), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 13.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 40.v, width: 54.h, margin: EdgeInsets.only(bottom: 5.v), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgUpload, height: 40.v, width: 54.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgLogo21, height: 25.v, width: 49.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 3.v))])), Container(width: 57.h, margin: EdgeInsets.only(left: 200.h, top: 5.v), child: Text("lbl_doctor_pharma".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargePoppinsWhiteA70013.copyWith(height: 1.44)))]))), SizedBox(height: 14.v), Text("lbl_your_balance".tr, style: CustomTextStyles.titleSmallPoppinsGray10003), SizedBox(height: 22.v), Text("lbl_237_00".tr, style: CustomTextStyles.titleLargePoppinsGray10003)])); } 
/// Section Widget
Widget _buildSubjectsRow(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h, right: 1.h), padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 10.v), decoration: AppDecoration.outlineGray6003f.copyWith(borderRadius: BorderRadiusStyle.roundedBorder7), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_transaction_history".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001SemiBold_1)), Spacer(), Padding(padding: EdgeInsets.only(top: 6.v), child: Text("lbl_view_all".tr, style: CustomTextStyles.bodySmallPoppinsBlack90001_2)), CustomImageView(imagePath: ImageConstant.imgG20541, height: 8.v, width: 5.h, margin: EdgeInsets.fromLTRB(6.h, 10.v, 4.h, 5.v))])); } 
/// Section Widget
Widget _buildNotificationList(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 2.h), child: BlocSelector<BrandInfotwoBloc, BrandInfotwoState, BrandInfotwoModel?>(selector: (state) => state.brandInfotwoModelObj, builder: (context, brandInfotwoModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 15.v);}, itemCount: brandInfotwoModelObj?.notificationlistItemList.length ?? 0, itemBuilder: (context, index) {NotificationlistItemModel model = brandInfotwoModelObj?.notificationlistItemList[index] ?? NotificationlistItemModel(); return NotificationlistItemWidget(model);});})); } 
/// Navigates to the invoicethreeOneScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.invoicethreeOneScreen, ); } 
 }
