import '../brand_infotwo_fourteen_screen/widgets/productcard6_item_widget.dart';import 'bloc/brand_infotwo_fourteen_bloc.dart';import 'models/brand_infotwo_fourteen_model.dart';import 'models/productcard6_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class BrandInfotwoFourteenScreen extends StatelessWidget {const BrandInfotwoFourteenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoFourteenBloc>(create: (context) => BrandInfotwoFourteenBloc(BrandInfotwoFourteenState(brandInfotwoFourteenModelObj: BrandInfotwoFourteenModel()))..add(BrandInfotwoFourteenInitialEvent()), child: BrandInfotwoFourteenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(left: 22.h, top: 14.v, right: 22.h), child: BlocSelector<BrandInfotwoFourteenBloc, BrandInfotwoFourteenState, BrandInfotwoFourteenModel?>(selector: (state) => state.brandInfotwoFourteenModelObj, builder: (context, brandInfotwoFourteenModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 319.v, crossAxisCount: 2, mainAxisSpacing: 21.h, crossAxisSpacing: 21.h), physics: BouncingScrollPhysics(), itemCount: brandInfotwoFourteenModelObj?.productcard6ItemList.length ?? 0, itemBuilder: (context, index) {Productcard6ItemModel model = brandInfotwoFourteenModelObj?.productcard6ItemList[index] ?? Productcard6ItemModel(); return Productcard6ItemWidget(model);});})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 22.v, bottom: 22.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_customer_ads".tr)); } 
/// Navigates to the invoicethreeOneScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.invoicethreeOneScreen, ); } 
 }
