import 'bloc/sign_up_three_bloc.dart';import 'models/sign_up_three_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/core/utils/validation_functions.dart';import 'package:dondondony38_s_application1/widgets/custom_icon_button.dart';import 'package:dondondony38_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:dondondony38_s_application1/presentation/sign_up_four_bottomsheet/sign_up_four_bottomsheet.dart';
// ignore_for_file: must_be_immutable
class SignUpThreeScreen extends StatelessWidget {SignUpThreeScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SignUpThreeBloc>(create: (context) => SignUpThreeBloc(SignUpThreeState(signUpThreeModelObj: SignUpThreeModel()))..add(SignUpThreeInitialEvent()), child: SignUpThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.all(36.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 182.h, margin: EdgeInsets.only(left: 4.h), child: Text("msg_create_an_account".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.displaySmall!.copyWith(height: 1.19)))), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 3.h), child: BlocSelector<SignUpThreeBloc, SignUpThreeState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "lbl_pharmacy_name".tr, hintStyle: CustomTextStyles.bodyMediumGray700, prefix: Container(margin: EdgeInsets.fromLTRB(17.h, 17.v, 7.h, 17.v), child: CustomImageView(imagePath: ImageConstant.img9042896pharmacysquaredcrossicon1, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 58.v), validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});})), SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 3.h), child: BlocSelector<SignUpThreeBloc, SignUpThreeState, TextEditingController?>(selector: (state) => state.phoneController, builder: (context, phoneController) {return CustomTextFormField(controller: phoneController, hintText: "lbl_pharmacy_phone".tr, hintStyle: CustomTextStyles.bodyMediumGray700, textInputType: TextInputType.phone, prefix: Container(margin: EdgeInsets.fromLTRB(18.h, 16.v, 5.h, 18.v), child: CustomImageView(imagePath: ImageConstant.img1564515calldevicemobilephonesmartphoneicon1, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 58.v), validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});})), SizedBox(height: 27.v), _buildPharmacyLicenseSection(context), SizedBox(height: 42.v), _buildSignUpSection(context), SizedBox(height: 5.v)]))))); } 
/// Section Widget
Widget _buildPharmacyLicenseSection(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 4.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_pharmacy_license".tr, style: CustomTextStyles.bodyMediumJFFlat_1), SizedBox(height: 5.v), Text("msg_please_upload_your".tr, style: CustomTextStyles.bodySmallJFFlatBluegray300), SizedBox(height: 14.v), GestureDetector(onTap: () {onTapEleven(context);}, child: Container(padding: EdgeInsets.symmetric(horizontal: 132.h, vertical: 26.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup18401, height: 35.adaptSize, width: 35.adaptSize, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 14.h)), SizedBox(height: 3.v), Text("lbl_attach_a_file".tr, style: CustomTextStyles.bodySmallJFFlatBluegray300), SizedBox(height: 2.v)]))), SizedBox(height: 38.v), BlocSelector<SignUpThreeBloc, SignUpThreeState, TextEditingController?>(selector: (state) => state.yourRegionController, builder: (context, yourRegionController) {return CustomTextFormField(controller: yourRegionController, hintText: "lbl_your_region".tr, hintStyle: CustomTextStyles.bodyMediumAlmaraiGray700, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 14.v, 11.h, 24.v), child: CustomImageView(imagePath: ImageConstant.img8665619maplocationicon1, height: 20.v, width: 22.h)), prefixConstraints: BoxConstraints(maxHeight: 58.v), contentPadding: EdgeInsets.only(top: 21.v, right: 30.h, bottom: 21.v));})])); } 
/// Section Widget
Widget _buildSignUpSection(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 10.v, bottom: 5.v), child: Text("lbl_sign_up".tr, style: theme.textTheme.headlineMedium)), CustomIconButton(height: 55.adaptSize, width: 55.adaptSize, padding: EdgeInsets.all(19.h), onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftWhiteA700))])); } 

/// Displays a bottom sheet widget using the [showModalBottomSheet] method 
/// of the [Scaffold] class with [isScrollControlled] set to true.
///
/// The bottom sheet is built using the [SignUpFourBottomsheet]
/// class and the [builder] method of the bottom sheet is passed the
/// [BuildContext] object.
onTapEleven(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>SignUpFourBottomsheet.builder(context),isScrollControlled: true); } 
/// Navigates to the homeFourContainerScreen when the action is triggered.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeFourContainerScreen, ); } 
 }
