import 'bloc/category_info_three_bloc.dart';import 'models/category_info_three_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class CategoryInfoThreeScreen extends StatelessWidget {const CategoryInfoThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CategoryInfoThreeBloc>(create: (context) => CategoryInfoThreeBloc(CategoryInfoThreeState(categoryInfoThreeModelObj: CategoryInfoThreeModel()))..add(CategoryInfoThreeInitialEvent()), child: CategoryInfoThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 36.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildSearchRow(context), SizedBox(height: 28.v), _buildLastSearchRow(context), Spacer(flex: 23), CustomImageView(imagePath: ImageConstant.imgHttpsLottief, height: 179.v, width: 264.h, margin: EdgeInsets.only(left: 47.h)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 109.h), child: Text("msg_there_is_no_search".tr, style: CustomTextStyles.bodyMediumOutfitGray50001)), Spacer(flex: 76)])))); } 
/// Section Widget
Widget _buildSearchRow(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 14.h), child: Row(children: [Expanded(child: BlocSelector<CategoryInfoThreeBloc, CategoryInfoThreeState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search_here".tr);})), GestureDetector(onTap: () {onTapTxtCancel(context);}, child: Padding(padding: EdgeInsets.only(left: 6.h, top: 17.v, bottom: 14.v), child: Text("lbl_cancel".tr, style: CustomTextStyles.bodyMediumOutfit)))])); } 
/// Section Widget
Widget _buildLastSearchRow(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 8.h, right: 13.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_last_search".tr, style: CustomTextStyles.titleMediumOutfitSemiBold), Padding(padding: EdgeInsets.symmetric(vertical: 2.v), child: Text("lbl_clear".tr, style: CustomTextStyles.bodySmallOutfitGray50001))]))); } 
/// Navigates to the homeFourContainerScreen when the action is triggered.
onTapTxtCancel(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeFourContainerScreen, ); } 
 }
