import '../brand_infotwo_nine_screen/widgets/productcardlist3_item_widget.dart';import 'bloc/brand_infotwo_nine_bloc.dart';import 'models/brand_infotwo_nine_model.dart';import 'models/productcardlist3_item_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_leading_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class BrandInfotwoNineScreen extends StatelessWidget {const BrandInfotwoNineScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoNineBloc>(create: (context) => BrandInfotwoNineBloc(BrandInfotwoNineState(brandInfotwoNineModelObj: BrandInfotwoNineModel()))..add(BrandInfotwoNineInitialEvent()), child: BrandInfotwoNineScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 22.v), _buildOrderDetailsRow(context), SizedBox(height: 42.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 17.h, right: 31.h, bottom: 5.v), child: Column(children: [_buildTotalRow(context), SizedBox(height: 21.v), _buildPaymentSummaryColumn(context), SizedBox(height: 24.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 15.h), child: Text("lbl_products".tr, style: CustomTextStyles.titleSmallPoppinsPrimarySemiBold))), SizedBox(height: 15.v), _buildProductCardList(context)]))))])))); } 
/// Section Widget
Widget _buildOrderDetailsRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 28.h, right: 13.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomAppBar(height: 27.v, leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgGroup1Black90001, margin: EdgeInsets.only(left: 29.h, top: 8.v, bottom: 7.v), onTap: () {onTapImage(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_order_details".tr)), SizedBox(height: 35.v), Padding(padding: EdgeInsets.only(right: 17.h), child: Text("msg_bill_no_23455_64327".tr, style: CustomTextStyles.titleMediumSemiBold)), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(right: 33.h), child: Text("msg_ordered_20_11_2023".tr, style: theme.textTheme.bodyMedium)), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_order_state".tr, style: CustomTextStyles.titleSmallPoppinsPrimarySemiBold)), SizedBox(height: 26.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomImageView(imagePath: ImageConstant.imgArrowDown, height: 9.v, width: 87.h, margin: EdgeInsets.only(right: 3.h))), Expanded(child: CustomImageView(imagePath: ImageConstant.imgTelevisionOrangeA200, height: 9.v, width: 87.h, margin: EdgeInsets.symmetric(horizontal: 3.h))), Expanded(child: CustomImageView(imagePath: ImageConstant.imgSettings, height: 9.v, width: 87.h, margin: EdgeInsets.only(left: 3.h)))]), SizedBox(height: 6.v), Align(alignment: Alignment.centerLeft, child: Container(width: 253.h, margin: EdgeInsets.only(left: 8.h, right: 17.h), child: Row(children: [Text("lbl_request_is_done".tr, style: CustomTextStyles.labelSmallPrimary), Spacer(flex: 44), Text("lbl_confirmed".tr, style: CustomTextStyles.labelSmallOrangeA200), Spacer(flex: 56), Text("lbl_on_the_way".tr, style: CustomTextStyles.labelSmallAmber600)])))])), Padding(padding: EdgeInsets.only(left: 7.h, top: 183.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgTelevisionLightGreen500, height: 9.v, width: 87.h), SizedBox(height: 6.v), Text("lbl_delivered".tr, style: CustomTextStyles.labelSmallLightgreen500)]))])); } 
/// Section Widget
Widget _buildTotalRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 17.h, right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_total".tr, style: CustomTextStyles.titleMediumPrimarySemiBold), Text("lbl_30_50".tr, style: CustomTextStyles.titleMediumPrimarySemiBold)])); } 
/// Section Widget
Widget _buildPaymentSummaryColumn(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 9.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 6.h), child: Text("lbl_payment_summary".tr, style: CustomTextStyles.titleMediumSemiBold))), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 9.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("msg_total_before_discount".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)), Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_50_50".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001))])), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 8.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("msg_total_after_discount".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)), Container(width: 192.h, margin: EdgeInsets.only(left: 3.h, top: 2.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("lbl_202".tr, style: CustomTextStyles.bodySmallPoppinsBlack90001)), Text("lbl_30_50".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)]))])), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_coupon_discount".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001), Text("lbl_00_00".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001)]))])); } 
/// Section Widget
Widget _buildProductCardList(BuildContext context) { return BlocSelector<BrandInfotwoNineBloc, BrandInfotwoNineState, BrandInfotwoNineModel?>(selector: (state) => state.brandInfotwoNineModelObj, builder: (context, brandInfotwoNineModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 14.v);}, itemCount: brandInfotwoNineModelObj?.productcardlist3ItemList.length ?? 0, itemBuilder: (context, index) {Productcardlist3ItemModel model = brandInfotwoNineModelObj?.productcardlist3ItemList[index] ?? Productcardlist3ItemModel(); return Productcardlist3ItemWidget(model);});}); } 
/// Navigates to the invoicethreeOneScreen when the action is triggered.
onTapImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.invoicethreeOneScreen, ); } 
 }
