import 'bloc/brand_infotwo_fifteen_bloc.dart';import 'models/brand_infotwo_fifteen_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_subtitle_three.dart';import 'package:dondondony38_s_application1/widgets/app_bar/appbar_title_image.dart';import 'package:dondondony38_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:dondondony38_s_application1/widgets/custom_elevated_button.dart';import 'package:dondondony38_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class BrandInfotwoFifteenScreen extends StatelessWidget {const BrandInfotwoFifteenScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<BrandInfotwoFifteenBloc>(create: (context) => BrandInfotwoFifteenBloc(BrandInfotwoFifteenState(brandInfotwoFifteenModelObj: BrandInfotwoFifteenModel()))..add(BrandInfotwoFifteenInitialEvent()), child: BrandInfotwoFifteenScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 18.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildLoremIpsumIsSimplyButton(context), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(right: 72.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgPlayPrimary, height: 39.v, width: 29.h, margin: EdgeInsets.only(top: 36.v)), _buildLoremIpsumIsSimplyDummyButton(context)])), SizedBox(height: 16.v), _buildLoremIpsumIsSiButton(context), SizedBox(height: 29.v), Padding(padding: EdgeInsets.only(right: 90.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgPlayPrimary39x29, height: 39.v, width: 29.h, margin: EdgeInsets.only(top: 36.v)), _buildLoremIpsumIsSimplyDummyTeButton(context)])), SizedBox(height: 9.v), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 242.h, right: 14.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 16.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderTL25), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), SizedBox(width: 104.h, child: Text("msg_lorem_ipsum_is_simply2".tr, maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.right, style: CustomTextStyles.labelLargePoppinsWhiteA70013_1))]))), SizedBox(height: 29.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgPlay39x29, height: 39.v, width: 29.h, margin: EdgeInsets.only(top: 36.v)), _buildLoremIpsumIsSimplyDuButton(context)]), SizedBox(height: 36.v), _buildMessageEditText(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 94.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 3.h, right: 219.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeftGray700, margin: EdgeInsets.only(top: 17.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), Container(height: 49.v, width: 51.000004.h, margin: EdgeInsets.only(left: 15.h), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPlay, height: 49.v, width: 51.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.img1181189ChatWechatIcon, height: 30.adaptSize, width: 30.adaptSize, alignment: Alignment.center, margin: EdgeInsets.fromLTRB(10.h, 8.v, 10.h, 10.v))])), AppbarSubtitleThree(text: "lbl_chat_with_us".tr, margin: EdgeInsets.only(left: 14.h, top: 14.v, bottom: 13.v))])), SizedBox(height: 15.v), Align(alignment: Alignment.centerLeft, child: SizedBox(width: 400.h, child: Divider(color: appTheme.gray200)))]), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildLoremIpsumIsSimplyButton(BuildContext context) { return CustomElevatedButton(height: 55.v, width: 208.h, text: "msg_lorem_ipsum_is_simply".tr, margin: EdgeInsets.only(right: 14.h), buttonStyle: CustomButtonStyles.fillPrimaryTL25, buttonTextStyle: CustomTextStyles.labelLargePoppinsWhiteA70013_1, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildLoremIpsumIsSimplyDummyButton(BuildContext context) { return Expanded(child: CustomElevatedButton(height: 56.v, text: "msg_lorem_ipsum_is_simply2".tr, margin: EdgeInsets.only(left: 4.h, bottom: 19.v), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.labelLargePoppinsGray800)); } 
/// Section Widget
Widget _buildLoremIpsumIsSiButton(BuildContext context) { return CustomElevatedButton(height: 56.v, width: 177.h, text: "msg_lorem_ipsum_is_si".tr, margin: EdgeInsets.only(right: 14.h), buttonStyle: CustomButtonStyles.fillPrimaryTL25, buttonTextStyle: CustomTextStyles.labelLargePoppinsWhiteA70013_1, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildLoremIpsumIsSimplyDummyTeButton(BuildContext context) { return Expanded(child: CustomElevatedButton(height: 56.v, text: "msg_lorem_ipsum_is_simply3".tr, margin: EdgeInsets.only(left: 4.h, bottom: 19.v), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.labelLargePoppinsGray800)); } 
/// Section Widget
Widget _buildLoremIpsumIsSimplyDuButton(BuildContext context) { return CustomElevatedButton(height: 56.v, width: 224.h, text: "msg_lorem_ipsum_is_simply4".tr, margin: EdgeInsets.only(left: 4.h, bottom: 19.v), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.labelLargePoppinsGray800); } 
/// Section Widget
Widget _buildMessageEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 18.h), child: BlocSelector<BrandInfotwoFifteenBloc, BrandInfotwoFifteenState, TextEditingController?>(selector: (state) => state.messageEditTextController, builder: (context, messageEditTextController) {return CustomTextFormField(controller: messageEditTextController, hintText: "msg_write_your_message".tr, textInputAction: TextInputAction.done, alignment: Alignment.center, prefix: Container(margin: EdgeInsets.symmetric(horizontal: 30.h, vertical: 16.v), child: CustomImageView(imagePath: ImageConstant.imgUserPrimary24x24, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 57.v), borderDecoration: TextFormFieldStyleHelper.outlineBlack, fillColor: appTheme.whiteA700);})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
