import '../sign_up_2_if_it_from_saudi_arabia_screen/widgets/password_item_widget.dart';import 'bloc/sign_up_2_if_it_from_saudi_arabia_bloc.dart';import 'models/password_item_model.dart';import 'models/sign_up_2_if_it_from_saudi_arabia_model.dart';import 'package:dondondony38_s_application1/core/app_export.dart';import 'package:dondondony38_s_application1/core/utils/validation_functions.dart';import 'package:dondondony38_s_application1/widgets/custom_icon_button.dart';import 'package:dondondony38_s_application1/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;
// ignore_for_file: must_be_immutable
class SignUp2IfItFromSaudiArabiaScreen extends StatelessWidget {SignUp2IfItFromSaudiArabiaScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SignUp2IfItFromSaudiArabiaBloc>(create: (context) => SignUp2IfItFromSaudiArabiaBloc(SignUp2IfItFromSaudiArabiaState(signUp2IfItFromSaudiArabiaModelObj: SignUp2IfItFromSaudiArabiaModel()))..add(SignUp2IfItFromSaudiArabiaInitialEvent()), child: SignUp2IfItFromSaudiArabiaScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: SizedBox(height: 818.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 40.h, top: 36.v, right: 36.h), child: Column(mainAxisSize: MainAxisSize.min, children: [Align(alignment: Alignment.centerLeft, child: SizedBox(width: 182.h, child: Text("msg_create_an_account".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.displaySmall!.copyWith(height: 1.19)))), SizedBox(height: 24.v), _buildCreateAnAccountStack(context), SizedBox(height: 18.v), _buildPasswordStack(context), SizedBox(height: 24.v), _buildConfirmPasswordTextStack(context)]))), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 64.v), decoration: BoxDecoration(image: DecorationImage(image: AssetImage(ImageConstant.imgGroup67), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 54.v), _buildUserStack(context), SizedBox(height: 17.v), Text("lbl_or".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001_1), SizedBox(height: 2.v), Text("msg_your_business_specialization".tr, style: CustomTextStyles.titleSmallPoppinsBlack90001_1), SizedBox(height: 30.v), _buildAiArtificialRow(context), SizedBox(height: 33.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 9.h, right: 58.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(padding: EdgeInsets.symmetric(horizontal: 59.h, vertical: 14.v), decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 49.adaptSize, width: 49.adaptSize, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.img2890580AiArtificial49x49, height: 49.adaptSize, width: 49.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.img8541696ClinicMedicalIcon, height: 21.v, width: 25.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 11.h, top: 11.v))])), SizedBox(height: 14.v), Text("lbl_clinic".tr, style: CustomTextStyles.titleSmallAlmaraiBlack90001), SizedBox(height: 2.v)])), Padding(padding: EdgeInsets.symmetric(vertical: 14.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgFacebook, height: 48.adaptSize, width: 48.adaptSize), SizedBox(height: 16.v), Text("lbl_hospital".tr, style: CustomTextStyles.titleSmallAlmaraiBlack90001)]))]))), SizedBox(height: 87.v), _buildContinueRow(context)])))]))))); } 
/// Section Widget
Widget _buildCreateAnAccountStack(BuildContext context) { return SizedBox(height: 106.v, width: 334.h, child: Stack(alignment: Alignment.bottomCenter, children: [BlocSelector<SignUp2IfItFromSaudiArabiaBloc, SignUp2IfItFromSaudiArabiaState, TextEditingController?>(selector: (state) => state.phoneController, builder: (context, phoneController) {return CustomTextFormField(width: 334.h, controller: phoneController, hintText: "lbl_phone".tr, hintStyle: CustomTextStyles.bodyMediumGray700, textInputType: TextInputType.phone, alignment: Alignment.topCenter, prefix: Container(margin: EdgeInsets.fromLTRB(18.h, 16.v, 6.h, 18.v), child: CustomImageView(imagePath: ImageConstant.img1564515calldevicemobilephonesmartphoneicon1, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 58.v), validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});}), BlocSelector<SignUp2IfItFromSaudiArabiaBloc, SignUp2IfItFromSaudiArabiaState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(width: 334.h, controller: emailController, hintText: "lbl_email".tr, hintStyle: CustomTextStyles.bodyMediumGray700, textInputType: TextInputType.emailAddress, alignment: Alignment.bottomCenter, prefix: Container(margin: EdgeInsets.fromLTRB(17.h, 16.v, 5.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgUserGray500, height: 25.adaptSize, width: 25.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 58.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});})])); } 
/// Section Widget
Widget _buildPasswordStack(BuildContext context) { return SizedBox(height: 64.v, width: 334.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.img9042896Pharmac, height: 29.adaptSize, width: 29.adaptSize, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 51.h)), BlocBuilder<SignUp2IfItFromSaudiArabiaBloc, SignUp2IfItFromSaudiArabiaState>(builder: (context, state) {return CustomTextFormField(width: 334.h, controller: state.passwordController, hintText: "lbl_password".tr, hintStyle: CustomTextStyles.bodyMediumAlmaraiGray700, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, alignment: Alignment.bottomCenter, prefix: Container(margin: EdgeInsets.fromLTRB(21.h, 18.v, 9.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgLocationGray500, height: 21.v, width: 16.h)), prefixConstraints: BoxConstraints(maxHeight: 58.v), suffix: InkWell(onTap: () {context.read<SignUp2IfItFromSaudiArabiaBloc>().add(ChangePasswordVisibilityEvent(value: !state.isShowPassword));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 11.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgEyeGray500, height: 21.adaptSize, width: 21.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 58.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword, contentPadding: EdgeInsets.symmetric(vertical: 21.v));})])); } 
/// Section Widget
Widget _buildConfirmPasswordTextStack(BuildContext context) { return SizedBox(height: 273.v, width: 338.h, child: Stack(alignment: Alignment.bottomLeft, children: [Align(alignment: Alignment.center, child: BlocSelector<SignUp2IfItFromSaudiArabiaBloc, SignUp2IfItFromSaudiArabiaState, SignUp2IfItFromSaudiArabiaModel?>(selector: (state) => state.signUp2IfItFromSaudiArabiaModelObj, builder: (context, signUp2IfItFromSaudiArabiaModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 59.v, crossAxisCount: 1, mainAxisSpacing: 1.h, crossAxisSpacing: 1.h), physics: NeverScrollableScrollPhysics(), itemCount: signUp2IfItFromSaudiArabiaModelObj?.passwordItemList.length ?? 0, itemBuilder: (context, index) {PasswordItemModel model = signUp2IfItFromSaudiArabiaModelObj?.passwordItemList[index] ?? PasswordItemModel(); return PasswordItemWidget(model);});})), Align(alignment: Alignment.bottomLeft, child: Padding(padding: EdgeInsets.only(left: 2.h, bottom: 8.v), child: Text("lbl_continue".tr, style: theme.textTheme.headlineMedium)))])); } 
/// Section Widget
Widget _buildUserStack(BuildContext context) { return GestureDetector(onTap: () {onTapUserStack(context);}, child: SizedBox(height: 147.v, width: 373.h, child: Stack(alignment: Alignment.centerRight, children: [Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(right: 6.h), padding: EdgeInsets.all(18.h), decoration: AppDecoration.outlineGray5003f01.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 55.v), CustomIconButton(height: 45.adaptSize, width: 45.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillWhiteA, child: CustomImageView(imagePath: ImageConstant.imgUserPrimary45x45))]))), Align(alignment: Alignment.centerRight, child: Container(height: 147.v, width: 112.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 40.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup70), fit: BoxFit.cover)), child: CustomImageView(imagePath: ImageConstant.imgArrowRightWhiteA700, height: 14.v, width: 7.h, alignment: Alignment.bottomRight))), Align(alignment: Alignment.topLeft, child: Container(width: 272.h, margin: EdgeInsets.only(left: 17.h, top: 18.v), child: Text("msg_you_can_now_order".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallPoppinsWhiteA700))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 35.v), child: Text("msg_log_in_as_a_personal".tr, style: CustomTextStyles.titleSmallPoppinsWhiteA700)))]))); } 
/// Section Widget
Widget _buildAiArtificialRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 9.h, right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 14.h), padding: EdgeInsets.symmetric(horizontal: 59.h, vertical: 14.v), decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.img2890580AiArtificialPrimary49x49, height: 49.adaptSize, width: 49.adaptSize), SizedBox(height: 14.v), Text("lbl_lab".tr, style: CustomTextStyles.titleSmallAlmaraiBlack90001)]))), Expanded(child: Container(margin: EdgeInsets.only(left: 14.h), padding: EdgeInsets.symmetric(horizontal: 47.h, vertical: 14.v), decoration: AppDecoration.outlineGrayF.copyWith(borderRadius: BorderRadiusStyle.roundedBorder14), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 48.adaptSize, width: 48.adaptSize, padding: EdgeInsets.all(9.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.img9042896Pharmac)), SizedBox(height: 16.v), Text("lbl_pharmacy".tr, style: CustomTextStyles.titleSmallAlmaraiBlack90001)])))])); } 
/// Section Widget
Widget _buildContinueRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 20.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 8.v), child: Text("lbl_continue".tr, style: theme.textTheme.headlineMedium)), CustomIconButton(height: 55.adaptSize, width: 55.adaptSize, padding: EdgeInsets.all(19.h), onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeft))])); } 
/// Navigates to the homeFourContainerScreen when the action is triggered.
onTapUserStack(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeFourContainerScreen, ); } 
/// Navigates to the signUpThreeScreen when the action is triggered.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUpThreeScreen, ); } 
 }
